name: cbq
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  flutter_riverpod: ^2.3.6
  go_router: ^6.5.8
  shared_preferences: ^2.1.0
  connectivity_plus: ^3.0.6
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lang/
  fonts:
    - family: Mulish-Light
      fonts:
        - asset: fonts/Mulish-Light.ttf
    - family: Mulish-Medium
      fonts:
        - asset: fonts/Mulish-Medium.ttf
    - family: Mulish-Regular
      fonts:
        - asset: fonts/Mulish-Regular.ttf
    - family: Mulish-SemiBold
      fonts:
        - asset: fonts/Mulish-SemiBold.ttf
    - family: Mulish-MediumItalic
      fonts:
        - asset: fonts/Mulish-MediumItalic.ttf
    - family: Mulish-Bold
      fonts:
        - asset: fonts/Mulish-Bold.ttf
    - family: Mulish-ExtraBold
      fonts:
        - asset: fonts/Mulish-ExtraBold.ttf
